yadm: Update bootstrap script
Apparently there's been some updates since I last put this
file in. I'm going to try it out and see how it feels.

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -5,33 +5,36 @@
 
 set -eu
 
+# Directory to look for bootstrap executables in
 BOOTSTRAP_D="${XDG_CONFIG_HOME:-$HOME/.config}/yadm/bootstrap.d"
 
-# Try the fallback if our preferred location does not work
-if [ ! -d "$BOOTSTRAP_D" ]; then
-    echo "Warning: bootstrap directory '$BOOTSTRAP_D' not found." >&2
-    echo "Trying fallback: $0.d" >&2
-    BOOTSTRAP_D="$0.d"
-fi
+# # Try the fallback if our preferred location does not work
+# if [ ! -d "$BOOTSTRAP_D" ]; then
+#     echo "Warning: bootstrap directory '$BOOTSTRAP_D' not found." >&2
+#     echo "Trying fallback: $0.d" >&2
+#     BOOTSTRAP_D="$0.d"
+# fi
 
 # If fallback fails, throw and error and exit
 if [ ! -d "$BOOTSTRAP_D" ]; then
-    echo "Error: Fallback bootstrap directory '$BOOTSTRAP_D' not found" >&2
+    # echo "Error: Fallback bootstrap directory '$BOOTSTRAP_D' not found" >&2
+    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
     exit 1
 fi
 
+find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
+    # 1. Check that the file is executable. If not an executable file, skip.
+    [ -x "$bootstrap" ] || continue
+    # 2. Check that the does not contain the substring '##' (ie
+    #    template files) nor end with '~' (ie editor backup files)
+    case "$bootstrap" in
+        *'##'*) continue ;;
+        *'~') continue ;;
+    esac
 
-find "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
-    # 1. Check that the file is executable
-    # 2. Check that the does not contain the substring '##' (ie template files)
-    # nor end with '~' (ie editor backup files)
-    if [ -x "$bootstrap" ] \
-    && ! echo "$bootstrap" | grep -e "##|~$" > /dev/null; then
-        # Check that the bootstrap file ran successfully. If not, throw an
-        # error.
-        if ! "$bootstrap"; then
-            echo "Error: bootstrap '$bootstrap' failed" >&2
-            exit 1
-        fi
+    # Check that the bootstrap file ran successfully. If not, throw an error.
+    if ! "$bootstrap"; then
+        echo "Error: bootstrap '$bootstrap' failed" >&2
+        exit 1
     fi
 done
